quarkus:
  http:
    port: 8088
  rest-client:
    telegram-api:
      url: https://api.telegram.org
    "com.lan.app.client.baserow.api.CoworkingGuestsApi":
      url: ${APP_BACKEND_URL:http://localhost:8080}
    "com.lan.app.client.baserow.api.CoworkingTariffsApi":
      url: ${APP_BACKEND_URL:http://localhost:8080}
    "com.lan.app.client.baserow.api.CoworkingMeetingRoomBookingsApi":
      url: ${APP_BACKEND_URL:http://localhost:8080}
    "com.lan.app.client.baserow.api.CoworkingActiveTariffsApi":
      url: ${APP_BACKEND_URL:http://localhost:8080}
    "com.lan.app.client.baserow.api.CoworkingNotificationsApi":
      url: ${APP_BACKEND_URL:http://localhost:8080}
    "com.lan.app.client.baserow.api.EventGuestsApi":
      url: ${APP_BACKEND_URL:http://localhost:8080}
    "com.lan.app.client.baserow.api.EventRegistrationsApi":
      url: ${APP_BACKEND_URL:http://localhost:8080}
    "com.lan.app.client.baserow.api.BotApi":
      url: ${APP_BACKEND_URL:http://localhost:8080}
    "com.lan.app.client.baserow.api.FestivalsApi":
      url: ${APP_BACKEND_URL:http://localhost:8080}
    "com.lan.app.client.baserow.api.CoworkingGuestTariffsApi":
      url: ${APP_BACKEND_URL:http://localhost:8080}
    logging:
      scope: request-response
      body-limit: 500
  default-locale: en
  locales:
    - en
    - ru
  openapi-generator:
    codegen:
      spec:
        baserow_api_json:
          base-package: com.lan.app.client.baserow
    baserow_api_json:
      auth:
        bearerAuth:
          bearer-token: ${API_TOKEN:}
  log:
    console:
      json: false
      color: true
      format: "%d{HH:mm:ss} %-5p [%c{2.}] %s%e%n"
    category:
      "com.lan.app.telegram":
        level: DEBUG
      "org.jboss.resteasy.reactive.client.logging":
        level: DEBUG

telegram:
  bot-token: ${TG_BOT_TOKEN}
  admin-chat-id: ${TG_ADMIN_CHAT_ID}
  api-base-url: https://api.telegram.org

app:
  site-url: ${APP_SITE_URL:}
  backend-url: ${APP_BACKEND_URL:}

"%dev":
  quarkus:
    devservices:
      enabled: false

  baserow:
    token: ${API_TOKEN:}
