quarkus:
  http:
    port: 3000
  rest-client:
    telegram-api:
      url: https://api.telegram.org
    "com.lan.app.client.baserow.api.CoworkingGuestsApi":
      url: ${BASEROW_URL:http://localhost:8080}
    "com.lan.app.client.baserow.api.CoworkingTariffsApi":
      url: ${BASEROW_URL:http://localhost:8080}
    "com.lan.app.client.baserow.api.CoworkingMeetingRoomBookingsApi":
      url: ${BASEROW_URL:http://localhost:8080}
    "com.lan.app.client.baserow.api.CoworkingActiveTariffsApi":
      url: ${BASEROW_URL:http://localhost:8080}
    "com.lan.app.client.baserow.api.CoworkingNotificationsApi":
      url: ${BASEROW_URL:http://localhost:8080}
  default-locale: en
  locales:
    - en
    - ru
  openapi-generator:
    codegen:
      spec:
        baserow_api_json:
          base-package: com.lan.app.client.baserow
    baserow_api_json:
      auth:
        bearerAuth:
          bearer-token: ${BASEROW_TOKEN}
  log:
    console:
      json: false
      color: true
      format: "%d{HH:mm:ss} %-5p [%c{2.}] %s%e%n"

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN}
  admin-chat-id: ${TELEGRAM_ADMIN_CHAT_ID}
  api-base-url: https://api.telegram.org
  webhook-secret: ${TELEGRAM_WEBHOOK_SECRET:}

app:
  mode: ${APP_MODE:polling}

"%prod":
  app:
    mode: webhook

"%dev":
  quarkus:
    devservices:
      enabled: false
  telegram:
    webhook-secret: ${TELEGRAM_WEBHOOK_SECRET:dummy-secret}

  baserow:
    token: ${BASEROW_TOKEN:}